spring.application.name=emailNotification
server.port=8081

# Database configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/email-notification?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1111
logging.level.org.hibernate.persister.entity=ERROR

# MVC configuration
spring.mvc.hiddenmethod.filter.enabled=true

# Email Sender configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kirilkitanov@gmail.com
spring.mail.password=twix ionl srdq qkwo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true